name: Build

on:
  push:
    branches:
      - main

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libavcodec-dev libavformat-dev libavutil-dev libglib2.0-dev clang-tools

      - name: Build with scan-build
        run: scan-build make dist

      - name: Upload binary
        uses: actions/upload-artifact@v7
        with:
          name: medialint-linux-x86_64
          path: bin/medialint
          retention-days: 14

  macos:
    name: macOS
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install deps
        run: brew install ffmpeg glib pkg-config

      - name: Build
        run: make dist CFLAGS=-std=c23

      - name: Upload binary
        uses: actions/upload-artifact@v7
        with:
          name: medialint-macos-arm64
          path: bin/medialint
          retention-days: 14

  windows:
    name: Windows
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up MSYS2
        uses: msys2/setup-msys2@4f806de0a5a7294ffabaff804b38a9b435a73bda # v.2.30.0
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-ffmpeg
            mingw-w64-ucrt-x86_64-glib2
            mingw-w64-ucrt-x86_64-pkg-config
            make

      - name: Build
        shell: msys2 {0}
        run: |
          make
          strip bin/medialint.exe
          ldd bin/medialint.exe | grep '/ucrt64/' | awk '{print $3}' | xargs -I{} cp {} bin/

      - name: Upload binary
        uses: actions/upload-artifact@v7
        with:
          name: medialint-windows-x86_64
          path: bin/
          retention-days: 14
